# Generated by Django 5.2.17 on 2026-10-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_synthetic',
            field=models.BooleanField(default=False),
        ),
    ]
