# Generated by Django 5.2.17 on 2026-09-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='is_negotiable',
            field=models.BooleanField(default=True),
        ),
    ]
