# Generated by Django 5.2.17 on 2026-09-28 18:38

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0004_backfill_application_deadline'),
        ('profiles', '0002_seed_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='gig',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='gig_search_vector_gin'),
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['status', '-created_at'], name='gig_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['status', 'category'], name='gig_status_category_idx'),
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['deadline'], name='gig_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['application_deadline'], name='gig_app_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['budget_min'], name='gig_budget_min_idx'),
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['budget_max'], name='gig_budget_max_idx'),
        ),
    ]
