# Generated by Django 5.2.17 on 2026-10-05 06:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0008_county_and_remote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GigInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('type', models.CharField(choices=[('view', 'View'), ('search_click', 'Search click'), ('save', 'Save'), ('apply', 'Apply')], max_length=20)),
                ('query', models.TextField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_synthetic', models.BooleanField(default=False)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='gigs.gig')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gig_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'gig'], name='interaction_user_gig_idx'), models.Index(fields=['type', 'created_at'], name='interaction_type_created_idx')],
            },
        ),
    ]
