# Generated by Django 5.2.17 on 2026-10-05 07:34

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0010_is_synthetic'),
        ('profiles', '0005_backfill_skills_and_seed_aliases'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gig',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='gig_title_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
