# Generated by Django 5.2.17 on 2026-10-05 06:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_freelancerprofile_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=100),
        ),
        migrations.CreateModel(
            name='SkillAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=100)),
                ('normalized_alias', models.CharField(editable=False, max_length=100, unique=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='profiles.skill')),
            ],
            options={
                'verbose_name_plural': 'Skill aliases',
                'ordering': ['alias'],
            },
        ),
    ]
